on:
  push:
    branches:
      - 1.8

name: Build and publish for branch 1.8
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: calyptia/fluent-bit-ci
          path: ci

      - name: Setup environment
        run: |
          sudo apt-get --yes update
          sudo apt-get install --yes docker.io containerd runc
          sudo systemctl unmask docker && sudo systemctl start docker

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build a docker image for master branch
        run: |
          DOCKER_BUILDKIT=1 docker build --no-cache -f ./dockerfiles/Dockerfile.${{ env.arch }} -t ${{ env.dockerhub_organization }}/fluent-bit:${{ env.arch }}-1_8_10 .
        env:
          arch: x86_64
          dockerhub_organization: egnbnd

      - name: Push image to Docker Hub
        run: |
          DOCKER_BUILDKIT=1 docker push ${{ env.dockerhub_organization }}/fluent-bit:${{ env.arch }}-1_8_10
        env:
          arch: x86_64
          dockerhub_organization: egnbnd
